### PR TITLE
Update title and note if release already exist

### PR DESCRIPTION
**Pull request by xoxys**
Fix https://github.com/drone-plugins/drone-github-release/issues/53

### CODE REVIEW

**Comment by xoxys** [comment]
@tboerger please review :)

**Comment by tboerger** [comment]
Do we really want to overwrite the release always? Or should we add an additional flag to enforce it?

**Comment by xoxys** [comment]
I don't really see a reason why we shouldn't but I can also add a `force` flag

**Comment by tboerger** [comment]
Or maybe overwrite

**Comment by xoxys** [comment]
Done. I've also limited the editRelease function to `title` and `note`, otherwise you can't handle different release types on the web ui without changes at your pipeline config.

**Comment by tboerger** [comment]
@appleboy if this is not already part of the gitea release plugin you should add it there as well :)

**Comment by xoxys** [comment]
@tboerger Currently it is not part of the gitea plugin. But for now, it will not work anyway because gitea does not trigger drone if you create a release from the UI (no tag event send)...

**Pull request merged**
