### PR TITLE
Implement prerelease option

### PR DESCRIPTION
**Pull request by tuxity**
Implement prerelease option when creating a new release

### CODE REVIEW

**Comment by bradrydzewski** [comment]
cc @tboerger since he is the mastermind behind this plugin :)

**Comment by tuxity** [comment]
**Drone-ui**:
screen shot 2017-03-23 at 4 28 23 pm
**Github**:
screen shot 2017-03-23 at 4 28 38 pm

**Comment by tboerger** [comment]
LGTM

**Comment by tuxity** [comment]
I've added the option in DOCS.md

**Pull request merged**
