### PR TITLE
[Feature] Consider all release types

### LINKED ISSUE #65: Publish a drafted release
First off: Thanks for this awesome Drone Plugin :)

I have the following config for pre-releases (and similar for releases)
```yaml
- name: pre-release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
      - _dist/*
    checksum:
      - sha256
    prerelease: true
  depends_on:
    - lint
    - test
    - build
  when:
    event:
      - tag
    ref:
      include:
        - "refs/tags/*rc*"
        - "refs/tags/*beta*"
        - "refs/tags/*alpha*"
```
In general, this works really well.
However, I'd like to achieve the following flow, which I'm used to from TravisCI:

1. I draft a release for tag vX.Y.Z
2. I trigger the drone pipeline by pushing tag vX.Y.Z
3. Drone builds the release files, picks up the draft release, updates it with the new details and publishes it

So in basic steps: Manually draft a Release -> Drone updates and publishes this release

Right now, Drone will just create a new release with the same tag, rendering the draft invalid.

### PR DESCRIPTION
**Pull request by iwilltry42**
Follow-Up on #68 (fixes #65) including fix for issue #71 as per comments below.

### CODE REVIEW

**Review by lafriks — APPROVED** [review]

**Comment by lafriks** [comment]
As #68 was reverted this needs new start taking into account issue #71

**Review by lafriks — CHANGES_REQUESTED** [review]
As per my previous comment :)

**Comment by iwilltry42** [comment]
@lafriks I pulled the original changes into this PR and rewrote it.
The error came from leftover, but now improper case handling, when no release was returned, but also no error was raised. It should be fixed now. Please give it a try.
(Relevant Lines: https://github.com/drone-plugins/drone-github-release/pull/69/files#diff-d839f0f9a2a680ce257706a246a02fc0a8ef3eb09212ae1d5085fa84c7dc7321R36-R49)

**Comment by tboerger** [comment]
@bradrydzewski could you just configure a pull-through cache for cloud.drone.io?

**Review by lafriks — APPROVED** [review]

**Comment by donny-dont** [comment]
@Upgreydd could you please take a look at this to make sure it works since you reported that failure?

**Comment by bradrydzewski** [comment]
the dry run needs to be removed because this results in unauthenticated pulls to dockerhub

**Comment by donny-dont** [comment]
@bradrydzewski the dry-run step is removed in #72

**Comment by donny-dont** [comment]
@iwilltry42 if you rebase the build should complete

**Comment by iwilltry42** [comment]
@donny-dont :heavy_check_mark:

**Pull request merged**
